### ISSUE TITLE
commented code

### ISSUE THREAD

**Issue by ecoppen** [alunity/Programming-challenges#2]
https://github.com/alunity/Programming-challenges/blob/a5d27e2faf64e179a6d3677f0e406e5e07a623bd/solutions/1/main.py#L1
https://github.com/alunity/Programming-challenges/blob/a5d27e2faf64e179a6d3677f0e406e5e07a623bd/solutions/1/main.py#L23-L30

I assume these are commented to ensure that testing completes without prompting for input?  The solution if this is the case is to put the input and output into different functions.

Then where you want to run the program, use:
```
if __name__ == '__main__':
    <starter_function_call_here>
```

This will only run if you're executing the current python file as the main program and not when imported, for things like tests.

**Comment by alunity** [comment]
Added starter functions in 223db78851e57f6b01749fcab9bc0212766c2939

I was wondering, what is the name of `if __name__ == '__main__':`. Is there a name? I feel like I've heard it being called the "main guard" but I'm not sure.

**Comment by ecoppen** [comment]
I think I've seen that term used once or twice however I just stick with 'top level code environment' which is from the docs - https://docs.python.org/3/library/__main__.html
