### ISSUE TITLE
Readable code?

### ISSUE THREAD

**Issue by ecoppen** [alunity/Programming-challenges#3]
https://github.com/alunity/Programming-challenges/blob/a5d27e2faf64e179a6d3677f0e406e5e07a623bd/solutions/20/main.py#L11

Should this be `else`? 

https://github.com/alunity/Programming-challenges/blob/a5d27e2faf64e179a6d3677f0e406e5e07a623bd/solutions/20/main.py#L24

How about `while not found`?

**Comment by alunity** [comment]
Added these changes in 223db78851e57f6b01749fcab9bc0212766c2939
